# Generated by Django 2.1.4 on 2019-04-15 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/vegetable', verbose_name='image'),
            preserve_default=False,
        ),
    ]
