# Generated by Django 2.1.4 on 2019-04-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/offers'),
        ),
    ]
