# Generated by Django 2.1.4 on 2019-04-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0003_auto_20190417_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='offers'),
        ),
    ]
